Error: matrix not being recognized by creatures in seperate .js files
- Added to client.js: fixed the drawing method by changing cearture values to intergers instead of the Creature_Ids in the  Creature classes